version: '3.8'
services:
  code-server:
    image: code-server-with-terraform
    container_name: code-server-terraform
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/home/coder/project
    command: --auth none
